### ISSUE TITLE
Bind not serving local addresses

### ISSUE THREAD

**Issue by alextall** [steamcache/steamcache-dns#10]
I just set up a new Ubuntu VM and set up steamcache and steamcache-dns containers. Steamcache-dns will answer non-local queries (i.e. google.com), but it does not reply with an answer to queries for locally stored addresses (i.e. steamcontent.com).

I have tried spinning up a fresh VM and setting up from scratch, but the issue persists. Any insight would be appreciated.

**Comment by alextall** [comment]
Another note: Following the setup instructions strictly, I received an error that the steamcache-dns container could not bind to port 53. Ubuntu still had systemd-resolve bound to the port. I was able to start the container after disabling systemd-resolved.service, but I wasn't sure if this was how it was intended.

**Comment by JasonRivers** [comment]
Regarding port 53/UDP already being in use, This is an issue with dnsmasq, it binds to 127.0.1.1:53, This means that you cannot use -p 53:53/udp to start the docker container, instead you should define your IP that you want it bound to.

For example, if you're IP is 10.0.0.100 you would use: -p 10.0.0.100:53:53/udp

To answer your initial question we're going to need more information, Please paste in the command you ran to run the container (docker run ...)

**Comment by alextall** [comment]
Thanks for the quick attention. I've updated my command with your advice on `-p` to below.
```shell
docker run --name stcamcache-dns -d --restart=always -p 10.0.100.184:53:53/udp -e STEAMCACHE_IP=$STEAMCACHE_IP steamcache/steamcache-dns
```
