### ISSUE TITLE
Problem Having the DNS to work.

### ISSUE THREAD

**Issue by TestCandidate** [steamcache/steamcache-dns#18]
NB: Please check the update below
Issue Description: 
I am running ubuntu 14.04 on VMWARE. 
was able to setup steamcache and steamcache-dns 
however, when i point my pc to the steamcache-dns IP, nothing is being resolved.

Docker Run Command:
```
sudo docker run --name steamcache -d -v /srv/steamcache/data:/data/cache -p 80:80 steamcache/steamcache:latest --restart=always


sudo docker run --name steamcache-dns -d --restart=always -p 192.168.43.43:53:53/udp -e STEAMCACHE_IP=192.168.43.43 steamcache/steamcache-dns
```

Docker Container Output:
without running in background, steamcache is stuck on nginx test successful, and steamcache-dns stuck on bind9 which i suppose is the correct behavior based on what i read in the previous closed issues.

what am i doing wrong ? 
can't seem to figure this out. any help is appreciated.

![image](https://cloud.githubusercontent.com/assets/22873773/26531885/ecbbf232-43fb-11e7-91e9-7165427abc62.png)

**************************************
**** UPDATE ****
**************************************
I noticed that BIND's config in your file did not have forwarding address.
so I changed my settings by adding google's public DNS  as a secondary DNS.
Now domains are being resolved.
The remaining problem is that all steam requests are going through the remote servers.
(tried uninstalling / reinstalling a game  3 times) and I'm checking your watchlog.sh script:

![image](https://cloud.githubusercontent.com/assets/22873773/26532057/2344762c-4400-11e7-8c79-f73631903218.png)

Any advise? 

Thanks

**Comment by TestCandidate** [comment]
Finally Got it to work. 
It was the cache's storage parameter. 
Sorry for the fuss.

**Comment by grm** [comment]
Hello testcandidate,

It seems i have th esame issue as you. 
I can see in the error.log : 
mkdir() "/data/cache/depot/234391" failed (2: No such file or directory) while reading upstream ..

What is the cache's storage parameter ?

Thx for your help.

**Comment by TestCandidate** [comment]
@grm  I just didn't give it any param and left it to default.
