### ISSUE TITLE
EA

### ISSUE THREAD

**Issue by madsjepsen0** [steamcache/steamcache-dns#21]
Issue Description:

Unable to connect to this site
Origina-a.akamaihd.net refused to connect.

It happens when you try to download origin on their website or will update origin

**Comment by astrolox** [comment]
This container will trap the traffic and send it to an internal IP.
Your symptoms would occur if you do that but then don't also run a reverse proxy for HTTP and HTTPS.
Please see https://steamcache.github.io/ for full instructions
