### ISSUE TITLE
Problems with Uplay caching function and how to disable it

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/steamcache-dns#22]
Issue Description:
Uplay is not being cached, the Uplay client does not display links and pages correctly and it is not possible to install games from the Uplay client.

Docker Run Command:
```
sudo docker run --name steamcache --restart=always -d -v /srv/steamcache/data:/data/cache -v /srv/steamcache/logs:/data/logs -v /srv/steamcache/info:/data/info -p 192.168.2.11:80:80 steamcache/steamcache:latest

sudo docker run --name lancache --restart=always -d -v /srv/lancache/data:/data/cache -v /srv/lancache/logs:/data/logs -v /srv/lancache/info:/data/info -p 192.168.2.12:80:80 steamcache/generic:latest

sudo docker run --name sniproxy --restart=always -d -p 443:443 steamcache/sniproxy:latest

sudo docker run --name steamcache-dns --restart=always -d -p 192.168.2.10:53:53/udp -e STEAMCACHE_IP=192.168.2.11 -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.2.12 -e UPLAYCACHE_IP=192.168.2.12 -e ORIGINCACHE_IP=192.168.2.12 steamcache/steamcache-dns:latest
```

Docker Container Output:

```
No docker output available
```

Both Steam and Origin are working flawless (after adding sniproxy).
When I use the docker config written above I am able to start the Uplay client but when I click on any game advertisement or any link it will give a 404 error message (will provide the exact error message tonight).

When I use 

```
sudo docker run --name steamcache-dns --restart=always -d -p 192.168.2.10:53:53/udp -e STEAMCACHE_IP=192.168.2.11 -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.2.12 -e ORIGINCACHE_IP=192.168.2.12 steamcache/steamcache-dns:latest -e DISABLE_UPLAY
```

to disable the Uplay cache I am still experiencing problems when I click on links in Uplay and try to install a Uplay game.

When I connect my game pc to the internet without using the docker machine as DNS server the Uplay client works perfectly.

I am using an Ubuntu 16.04 machine with Docker installed but I am not an experienced Ubuntu or Docker user (but willing to learn!).

**Comment by JohanvdHoven** [comment]
I tried changing the docker command line syntax:
```
sudo docker run --name steamcache-dns --restart=always -d -p 192.168.2.10:53:53/udp -e STEAMCACHE_IP=192.168.2.11 -e USE_GENERIC_CACHE=true -e DISABLE_UPLAY -e LANCACHE_IP=192.168.2.12 -e ORIGINCACHE_IP=192.168.2.12 steamcache/steamcache-dns:latest
```
Unfortunateley this does not solve the issue.
I can logon to Uplay but news items doe not get displayed and I cannot install any of my games.

**Comment by astrolox** [comment]
At a guess I assume your problem might be DISABLE_UPLAY needing a value to be specified.
Instead of `-e DISABLE_UPLAY` try `-e DISABLE_UPLAY=true`

**Comment by JohanvdHoven** [comment]
Thank you for explaining what I was doing wrong.
With the =true statement the UPLAY caching function can be disabled successfully!

However when I enable it unfortunately still does not work like the Steam and Origin caches as it gives an internet connection error when i try to download a game in the Uplay client.

**Comment by voodoodrul** [comment]
+1
