### ISSUE TITLE
Upstream DNS

### ISSUE THREAD

**Issue by jimnordb** [steamcache/steamcache-dns#23]
Issue Description:
Upstream DNS not working

Docker Run Command:
docker run --name steamcache-dns -p 53:53/udp -e STEAMCACHE_IP=192.168.1.21 -e UPSTREAM_DNS=192.168.1.1 steamcache/steamcache-dns:latest

The upstream DNS is not working when using my host (in this case 192.168.1.21) i see the update came only 9 hours ago. and i haven't had the time to dig around with how sed commands work

**Comment by astrolox** [comment]
I recommend also specifying the dns flags in your docker run.
i.e. `docker run --dns 192.168.1.1 ....`

**Comment by kanonfodda** [comment]
I have the same issue.  Both -e UPSTREAM_DNS and --dns are set on the command line, but internal DNS resolution is not working through the steamcache-dns.

Command line is:  
docker run --name steamcache-dns -p 10.114.32.38:53:53/udp -e STEAMCACHE_IP=10.114.32.38 steamcache/steamcache-dns:latest --dns 10.114.32.90 -e UPSTREAM_DNS=10.114.32.90

**Comment by neothor** [comment]
I have the same issue. Specified both env variable and dns in docker-compose file. When I do a nslookup from the container I get a hit. But when I use the nslookup against the dns server I get nothing.

**Comment by krandor** [comment]
Sorry to necro, but i was able to get local DNS working by editing the bind configuration of the container.

I created a new zone file local.named.conf in /etc/bind/ and added forwarding information for my local domain:

> zone "mydomain.local" { #internal domain name
        type forward;
        forward only;
        forwarders { 192.168.10.1; }; #my internal DNS server
};
zone "10.168.192.in-addr.arpa" { #the subnet of the internal domain
        type forward;
        forward only;
        forwarders { 192.168.10.1;}; #my intermal DNS server
};


I then added the file to be included in named.conf:

>include "/etc/bind/named.conf.options";
include "/etc/bind/local.named.conf"; #not sure if order matters?
include "/etc/bind/cache.conf";

Lastly, i edited named.conf.options:

>acl goodclients {
   192.168.10.0/24; #"external" network to allow
   localhost;
   localnets;
};
options {
        directory "/var/cache/bind";
        dnssec-enable yes;
        dnssec-validation yes;
        auth-nxdomain no;    # conform to RFC1035
        recursion yes;
        allow-recursion { any; };
        allow-query { goodclients; };
        allow-query-cache { any; };
        listen-on { any; };
        listen-on-v6 { any; };
        forwarders {
                192.168.10.1; #my local DNS server
        };
};

I used a combination of the following pages to put this together
[Digital Ocean Guide](https://www.digitalocean.com/community/tutorials/how-to-configure-bind-as-a-caching-or-forwarding-dns-server-on-ubuntu-14-04)
[Stackoverflow](https://serverfault.com/questions/99101/conditional-dns-forwarding-with-named-on-linux)

**Comment by JasonRivers** [comment]
Closing as I believe this issue is solved as of 52638595 Please open a new issue if you are still having problems.

@krandor We don't recommend you modify the container in this way, I don't think this has anything to do with the issue reported.

**Comment by krandor** [comment]
oops, you're right. I've been running around the internet trying to get my issue figured out. I must have commented on the wrong tab.
