### ISSUE TITLE
edge.steam-dns.top.comcast.net is used instead of my generic cache

### ISSUE THREAD

**Issue by Jheguy2** [steamcache/steamcache-dns#26]
All of my downloads appear to be using edge.steam-dns.top.comcast.net no matter if I use the DNS container. Services like Origin and Blizzard work great but strangely I cannot get steam to work or find a way to disable these Comcast mirrors. My device is directly using the DNS from the docker container and I flushed my DNS cache just to be certain it wasn't just something that happened before I began caching my downloads. Any suggestions on how I could fix this? Thanks!

**Comment by JasonRivers** [comment]
Could you try restarting the DNS container with ```-e UPSTREAM_DNS=8.8.8.8``` and see what steam does then? You may have to flush dns cache.

**Comment by Jheguy2** [comment]
Went ahead and created a new DNS container with the UPSTREAM_DNS set to 8.8.8.8 and it still does the same thing. It's very strange as if I observe Wireshark, it actually does a query for valve801.steamcontent.com (which resolves to my generic caching container) and then queries for edge.steam-dns-top.comcast.net which resolves to 68.87.56.18. It then solely uses that server to complete the download and never touches my container. I have tried both the generic container and steamcache and both result in the same pattern. Very strange.

**Comment by palodich** [comment]
I suspect I'm having the same issue. I set up Steamcache a month ago, and I immediately suspected only a portion of the traffic was getting cached, and now after last week no traffic is. The only thing that shows up in the logs is GET /server-status and GET /serverlist/76/20/ .

I'm not a Wireshark pro, what filter are you using in Wireshark to monitor the traffic?

**Comment by Marashni** [comment]
Can confirm this is my issue as well. I at first assumed it was related to this: https://github.com/steamcache/generic/issues/26 

However, it turns out much of my traffic is redirected to the Comcast mirrors.

As @mintopia points out in that link above, the steam content_log.txt file in the steam client directory shows DNS not being redirected for edge.steam-dns.top.comcast.net

**Comment by ayancey** [comment]
I can confirm I'm having the same problem as well.

**Comment by Marashni** [comment]
I believe we just need to add that Comcast mirror to the list of legitimate steam mirrors.

**Comment by JasonRivers** [comment]
We are currently discussing this, We are looking at populating the DNS for this image from here: https://github.com/uklans/cache-domains

We'll be making sure that the comcast domains are in there, but this requires some work to be fully automated when new domains are added, We also have to discuss how we enable/disable particular domains as the current system may get a bit too heavy with the number of services we support with the uklans caching.

**Comment by jarredwalton** [comment]
Was this ever solved? I'm using lancache, which is similar in practice, and I'm getting most of my Steam traffic hitting edge.steam-dns.top.comcast.net and edge.steam-dns-2.top.comcast.net

I've tried adding those to my unbound.conf, but still not sure it's working properly.

**Comment by palodich** [comment]
There haven't been any changes since November, so it hasn't been fixed.

**Comment by JasonRivers** [comment]
We are now building the DNS from [uklans/cache-domains](https://github.com/uklans/cache-domains), This way we only have a single place to change the domains.
I have issued a [PR](https://github.com/uklans/cache-domains/pull/19) there for the comcast domain

**Comment by Superfish1000** [comment]
I have had this same issue with Squid based caching on pfsense.  I solved it by blocking port 443 access to Comcast's in house CDNs

# http://edge.steam-dns.top.comcast.net
# http://edge.steam-dns-2.top.comcast.net

The issue has been completely resolved after this.  I'm going to attempt HTTPS bumping on those domains later by adding them to a ACL on my firewall.  I found this while looking to see if anyone else had written about it.

Hope this helps.
