### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Yogi85** [steamcache/steamcache-dns#28]
Hello everybody

I do not understand what exactly needs to be done with the dockerfile. Can someone tell me that?

Thank you

Gruess Yogi85

**Comment by JasonRivers** [comment]
The Docker file is used to create the docker container image which is hosted on https://hub.docker.com/r/steamcache/steamcache-dns You can run this from within docker by running the command in the Usage example.

This container is only DNS settings for a network, and will require the cache to be running on your network, for example, my config using a docker-compose is:
```version: '2'
services:
  Steamcache:
    image: steamcache/steamcache
    volumes:
    - /DockerVolumes/steamcache/cache:/data/cache
    - /DockerVolumes/steamcache/logs:/data/logs
    - /DockerVolumes/steamcache/info:/data/info
    ports:
    - 80:80/tcp
  Steamcache-dns:
    image: steamcache/steamcache-dns
    environment:
      STEAMCACHE_IP: ${STEAMCACHE_IP}
      DISABLE_BLIZZARD: 'true'
      DISABLE_ORIGIN: 'true'
      DISABLE_FRONTIER: 'true'
      DISABLE_RIOT: 'true'
      DISABLE_UPLAY: 'true'
      DISABLE_WINDOWS: 'true'
    ports:
    - 53:53/udp
```

If you are not familiar with Docker, please read their documentation at https://docs.docker.com/
