### ISSUE TITLE
Download speed is not stable when pointing to local cache 

### ISSUE THREAD

**Issue by AlaaAkoum** [steamcache/steamcache-dns#37]
Issue Description:
After installing steamcache-dns docker  , we pointed update server to  the local cache server
then it started downloading for the first time and cache server started to cache data 
then we faced download speeds spikes download to 0 kb 
![image](https://user-images.githubusercontent.com/34676802/43336643-5f575ebc-91da-11e8-9ee0-3e26e186d34a.png) 

if i try to change my pc dns to public dns the download is stable and without spikes 

Docker Run Command:
```
sudo docker run --name steamcache-dns --restart=always -d -p 53:53/udp -e STEAMCACHE_IP=192.10.11.246 steamcache/steamcache-dns:latest
```

Docker Container Output:

```
<!-- If there is output from the container regarding this issue, paste it here -->
```

**Comment by JasonRivers** [comment]
I don't think this is an issue for the DNS container unless you're getting DNS misses, Please raise this issue on either [steamcache/steamcache](https://github.com/steamcache/steamcache) or [steamcache/generic](https://github.com/steamcache/generic) depending on which you are running for your cache.
