### ISSUE TITLE
DNS not working with windows update cache

### ISSUE THREAD

**Issue by Nusux** [steamcache/steamcache-dns#40]
Issue Description:

When only using the windows update cache the steamcache-dns keeps restarting.

Docker Run Command:

sudo docker run \
  --restart unless-stopped -d \
  --name steamcache-dns \
  -p 192.168.2.230:53:53/udp \
  -e UPSTREAM_DNS=8.8.8.8 \
  -e WINDOWSCACHE_IP=192.168.2.230 \
  steamcache/steamcache-dns:latest

Log output:
Bootstrapping DNS from https://github.com/uklans/cache-domains
Creating apple template
Creating arenanet template
Creating blizzard template
Creating daybreak template
Creating frontier template
Creating gog template
Creating hirez template
Creating minecraft template
Creating nexusmods template
Creating nintendo template
Creating origin template
Creating riot template
Creating rockstar template
Creating sony template
Creating steam template
Creating uplay template
Creating twitch template
Creating wargaming template
Creating wsus template
Creating xboxlive template

 --- 

Enabling WINDOWS on IP 192.168.2.230
creating /etc/bind/cache/windows.db
sed: /etc/bind/cache/windows.db: No such file or directory

**Comment by JasonRivers** [comment]
Thanks for the report, I will take a look in to this.

**Comment by Nusux** [comment]
Found the solution:
instead of "-e WINDOWSCACHE_IP=192.168.2.230" it has to be "-e WSUSCACHE_IP=192.168.2.230"

**Comment by JasonRivers** [comment]
Ah yes, because the service name from uklans is wsus, Good catch! I'll make a note to update the README so it has all of the service names, That shouldn't be difficult to automate at all.
