### ISSUE TITLE
Can't running in Raspberry Pi

### ISSUE THREAD

**Issue by oniyakun** [steamcache/steamcache-dns#41]
Issue Description:

Linux ubuntu 4.14.58 (Including raspbian and debian) for raspberry pi3b+, can't run the docker

Docker Run Command:
```
<!-- sudo docker run --name steamcache --restart=always -d -v /disk/steam/data:/data/cache -p 80:80 steamcache/steamcache:latest -->

<!-- sudo docker run --name steamcache-dns --restart=always -d -p 53:53/udp -e STEAMCACHE_IP=192.168.0.106 steamcache/steamcache-dns:latest -->
```

Docker Container Output:

```
<!--standard_init_linux.go:190: exec user process caused "exec format error" -->
```

**Comment by JasonRivers** [comment]
The steamcache/lancache stack only support AMD64/x86_64 architectures, We currently have no plans to support the Raspberry pi / ARM as the stack requires a large amount of memory.
