### ISSUE TITLE
steamcache-dns container not starting

### ISSUE THREAD

**Issue by QuattroViper** [steamcache/steamcache-dns#43]
Issue Description:
The container consistently tries to restart, but does not succeed. 
The main server IP is 192.168.2.10.

The other docker files from steamcache are all up and running, but steamcache-dns keeps crashing. 

Docker Run Command:

sudo docker run \
  --restart unless-stopped -d \
  --name steamcache-dns \
  -p 192.168.2.10:53:53/udp \
  -e UPSTREAM_DNS=192.168.2.222 \
  -e STEAMCACHE_IP=192.168.2.11 \
  -e ORIGINCACHE_IP=192.168.2.12 \
  -e BLIZZARDCACHE_IP=192.168.2.13 \
  -e RIOTCACHE_IP=192.168.2.14 \
  -e WINDOWSCACHE_IP=192.168.2.15 \
  -e DISABLE_UPLAY=true \
  -e DISABLE_FRONTIER=true \
  steamcache/steamcache-dns:latest

Docker Container Output:
STATUS = Restarting (2) 35 seconds ago

Side Note: How do I add my own Domains/records to the Uklans-DNS? My steam connects to a IP that is not in the Uklans records.

**Comment by JasonRivers** [comment]
Does the DNS running on 192.168.2.222 point back to the steamcache-dns container for upstreams? The DNS container needs to talk to the internet to get the list of DNS records from uklans, it's best to set the upstream DNS to something outside of your network if you can. Are you able to get the logs from the container?

On a side not - you're using WINDOWSCACHE_IP, this should be WSUSCACHE_UP as the service name is the same as what is set on uklans.

If steam is downloading from a domain not in UKLans (and it's not one that you've generated), then the best place to add this is in uklans.

**Comment by QuattroViper** [comment]
The DNS on 192.168.2.222 points to the IP 8.8.8.8 . But I have changed the Upstream for testing to 8.8.8.8 .
I also changed the the service name to the one you said. 
The IP steam connects to is: - 'edgecast.cdn.steampipe.steamcontent.com', but it falls probably under the *.steamcontent.com filter?

After hours of struggling, I found the logs. I needed to add the -e LANCACHE_IP with the -e USE_GENERIC_CACHE=true argument. 
I also tried it in the beginning. But I got WINDOWSCACHE_IP wrong which was the error there. 

It is resolved now. In the end, it was just the WINDOWSCACHE_IP mishap that was the problem.

Thank you.

**Comment by QuattroViper** [comment]
The container is running now. But the downloads is still not cached. I changed the upstream IP to 8.8.8.8 and it still goes past the DNS server.

**Comment by blairmacintyre** [comment]
Weirdly, I just started having similar problems;  my steamcache-dns is no longer working.  If I look at my steamcache log, the last thing served up was a yesterday, and if I do `nslookup - 192.168.4.164` (ip of the server) it doesn't respond.

I tried restarting, and got a similar status as you had above.

If I do `docker logs steamcache-dns` there's a series of 
```
Running bootstrap.sh...
Enabling cache for Blizzard
Enabling cache for Frontier
Enabling cache for Origin
Enabling cache for Riot
Enabling cache for Steam
Enabling cache for Uplay
Enabling cache for Windows
Enabling custom DNS forwarder
bootstrap finished.
checking Bind9 config
Running Bind9
Bind9 exited with 1```

entries.  

I stopped and `docker rm`'d the image, and reran it, to no avail.  I'm at a loss as to what could be wrong.

**Comment by VibroAxe** [comment]
@QuattroViper at a guess this is one of two things:

1) You are handing out two dns servers from your dhcp server, the router and the steamcache-dns. Check that your computer ONLY has steamcache-dns

2) You image is missing some of the latest domains from uklans/cache-domains, try repulling.
