### ISSUE TITLE
Windows 10 Updates - unable to connect to update service

### ISSUE THREAD

**Issue by andyle2k** [steamcache/steamcache-dns#53]
Windows 10 updates no longer working; error "unable to connect to updates service"

Was previously working fine. 

Confirmed that Windows 7 updates work fine and are being cached as intended. 

Don't know if issue is with this container or with the domains list. I've added this issue on the UKLANS git as well:
https://github.com/uklans/cache-domains/issues/39#issue-372358499

Thanks.

**Comment by VibroAxe** [comment]
Related issue closed
