### ISSUE TITLE
No internet access on the server running docker containers

### ISSUE THREAD

**Issue by eliasteeny** [steamcache/steamcache-dns#54]
Issue Description:
I have a ubuntu server and i want to access it from outside my lan and i can't use ssh because i can't configure port forwarding so i want to use teamviewer but there is no internet access on the server but pinging 8.8.8.8 works flawlessly 

Docker Run Command:
```
sudo docker run --restart unless-stopped -d --name steam-cache -p 192.168.1.4:80:80 steamcache/generic:latest

sudo docker run --restart unless-stopped -d --name steamcache-dns -p 192.168.1.4:53:53/udp -e STEAMCACHE_IP=192.168.1.4 steamcache/steamcache-dns:latest

```
I'm not sure if steamcache/steamcache-dns or steamcache/generic is causing this.

**Comment by sta3b** [comment]
hey, first of all you should run sniproxy too : 
sudo docker run --name prox --restart=always -d -p 443:443 steamcache/sniproxy:latest
(for HTTPS requests)
secondly i am pretty sure its an IP issue or a Mikrotik Issue . try setting a manual DNS server 1.1.1.1 or 8.8.8.8 from the ubuntu network settings, if it doesn't work you probably need to check ur router/mikrotik configuration maybe some firewall rules, mangle rules.. 
and finally make sure u are running the latest updates for ubuntu :  
sudo apt-get update
sudo apt-get upgrade

**Comment by VibroAxe** [comment]
@sta3b thanks for offering to help with this, but please keep people in the issues so that we can provide official support if required
