### ISSUE TITLE
Other Zones?

### ISSUE THREAD

**Issue by en3r0** [steamcache/steamcache-dns#6]
On the Generic cache page it says: "Note: steamcache-dns does not currently support these providers. It will be updated soon."

Wondering if that was still on the way?

**Comment by adrianmace** [comment]
I would like to say that I'll be rolling out this software immediately to the largest gaming lounge in Melbourne, Australia when the other zones start being covered by steamcache-dns!

**Comment by JohanvdHoven** [comment]
I am awaiting this update as well.

**Comment by JasonRivers** [comment]
PR #3 adds this, we're working on merging the changes in.
