### ISSUE TITLE
Not resolving all Zones

### ISSUE THREAD

**Issue by Fischje** [steamcache/steamcache-dns#7]
I installed docker for ubuntu as the docs say.
I run the steamchace-dns and steamcache container.

nslookup of content1.steampowered.com runs to my server.
nslookup of content6.steampowered.com results:

C:\Users\Fischje>nslookup content6.steampowered.com
Server:  UnKnown
Address:  192.168.178.178

Nicht autorisierende Antwort:
Name:    edge.steam-dns.top.comcast.net
Addresses:  2001:558:fe03:6d::2
          2001:558:fe03:31::2
          2001:558:fe03:5::2
          2001:558:fe03:57::2
          69.241.35.98
          69.241.8.130
          69.241.35.134
          69.252.112.206
Aliases:  content6.steampowered.com

Can someone help me?

**Comment by JasonRivers** [comment]
You will need to point your local DNS server to the docker container. The best way to do this is on your router assuming that your steam cache is up at all times.

As long as you used -p 53:53/udp when starting the DNS container, you just need to point your DNS server to the computer you ran the container on. You can check that your steamcache-dns is working correctly before you do this with the following commands:

Windows:
```
nslookup content6.steampowered.com ${DNS-IP}
```

Linux:
```
dig content6.steampowered.com @${DNS-IP}
```

Where ${DNS-IP} is the IP address of the computer that you ran the steamcache-dns container on.

**Comment by Fischje** [comment]
Works finde now cause:
1. the clinet i tried does not resolv correcty - tried everything. all other clients in my lan done it correct. maybe the client itself - will install this win new.
2. i took my sopos utm and redirect all zone entries direct from that to the cacheing docker ;)
could be closed...
